### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Futuremappermydud** [gidodidi/BMBF#1]
i think we could get a compatibility mode where it takes the asset name+ type and searches the asset, finds the sharedassets and changes the bmbfmod.json

**Comment by Futuremappermydud** [comment]
+ change bmbfdata in quest to also use beatondata so we dont have to mess with a bunch of settings and junk

**Comment by RedBrumbler** [comment]
so for the first thing you are saying to do the thing it already does? you can just preload all asset files instead, and it will do the thing you describe

it's not very efficient though

the second thing, why? you can just copy over your data, and I heard it automatically renames beatondata to bmbfdata

**Comment by Futuremappermydud** [comment]
ok thanks
