### ISSUE TITLE
Saber mods

### ISSUE THREAD

**Issue by komiveslab** [gidodidi/BMBF#2]
Saber Mods do not upload(MacOS Catalina, chrome browser)
<img width="326" alt="Screen Shot 2019-10-09 at 7 18 23 PM" src="https://user-images.githubusercontent.com/20055340/66533960-9cb5d880-eac9-11e9-8612-619d03dd771b.png">

**Comment by Arakon** [comment]
Rename the .json file inside the zip to bmbfmod.json.

**Comment by RedBrumbler** [comment]
this place has all mods updated (in theory, if anything breaks let me know)
https://github.com/RedBrumbler/BMBFCustomSabers
